### ISSUE TITLE
out of service?

### ISSUE THREAD

**Issue by tomdavidson** [pyther/podfeed#1]
http://npr.pyther.net/ has been done for several days ... Im freaking out and now longer know what going on in the world without my daily fix of All Things Considered and Morning Edition!

Seriously, whats up? Can I help?

**Comment by pyther** [comment]
Sorry about that! I migrated to a new host and forgot to have apache (the web server) start when the system booted. It should be working again, let me know if you have any problems.

**Comment by tomdavidson** [comment]
I'm a cloud/devops engineer. If you ever want to automate it all, terraform
it, set up continuous delivery... Im happy to help - really appreciate the
project. Thanks for fix it right away.

**Comment by tomdavidson** [comment]
@pyther hello again! 

Short outages are fairly common, but the current one has been 3 days. I still don't know anything about flask but might be able to help with other stuff if wanted.

**Comment by pyther** [comment]
The service is dead. Unfortunately, NPR has deprecated the api that I was using to pull this data. The new API is very focused around NPR One there wasn't an immediate way that I saw to extract content. Sorry. It was good while it lasted.

**Comment by pyther** [comment]
@tomdavidson good news, I was able to revive the project. The service should be back online. Let me know if you notice any issues. I am now manually generating the podcast rss feeds.

**Comment by tomdavidson** [comment]
Sweet and thank you!

You are taking a JSON response and creating the RSS feed?

Came across an API request that I started using on Saturday.  Is this the old API? 
http://api.npr.org/query?id=3&date=currentwithaudio&sort=assigned&output=podcast&sc=17&numResults=50&apiKey=XXXXX

**Comment by pyther** [comment]
That is the legacy api and it is no longer possible to get an api key, from what i can tell. The new code loads the npr program page and looks for the`data-play-all` attribute which contains a json object of all segments for an episode. From that I generated a rss feed based on that data.

**Comment by tomdavidson** [comment]
Ha, I love it! Much better than a typical screen scrape. Thank you.
